name: mailwork
summary: Web and API based SMTP testing
description: |
 MailWork is an email testing tool for developers:
 * Configure your application to use MailWork for SMTP delivery
 * View messages in the web UI, or retrieve them with the JSON API
 * Optionally release messages to real SMTP servers for delivery
version: "master"
confinement: strict
grade: stable
apps:
  mailwork:
    command: MailWork
    plugs: [network-bind]
    daemon: simple
parts:
  mailwork:
    plugin: go
    go-packages:
      - MailWork
    build-packages:
      - git
